// This file is auto-generated by `payload generate:importmap`.
// It must exist for the admin to mount. Run that command after adding any
// custom UI overrides to repopulate this file.
export const importMap = {};
